### ISSUE TITLE
Turns off immediately after setting to heat.

### ISSUE THREAD

**Issue by solve-salvesen** [JDolven/Replacing-HF_LPT120A-in-a-millheat-heater#6]
I have 3 modded Mill heaters in my cabin. It works good, but now and then i struggle to get the heater on via HA. I set mode to heat, but it returns to off after a small second or so. This happens on all 3 just now. I use Esphome logging and can se that mode changes to heat, and then back again but i do not know if it is HA that turns it off immediately or if it is the D1 mini. What I also see is that temperatur is logged as NaN. The wifi coverage is good. 

I have tried to add web server through Esphome, but there it also turns off immediately, so maybe nothing to do with HA afrer all.

Winter is coming so I have now turned off the power optimizing of the heaters so that they are on all the time, when they finally turn back on again.

After some time suddenly the heater is in heat mode and everything is fine. Does anyone know why this happens?

![2024-11-08 09_23_39-ESPHome – Home Assistant](https://github.com/user-attachments/assets/79addf1a-51c6-4ad3-9db8-908cbeab4598)
![2024-11-08 09_23_58-Overview – Home Assistant](https://github.com/user-attachments/assets/5e6bff19-af47-4f6c-a946-83687ccce7f9)

**Comment by JDolven** [comment]
I can’t replicate the error right now, but I had something similar happen before. Back then, it was an automation / Node-RED that messed with me.

**Comment by solve-salvesen** [comment]
Thanks for your reply. I will investigate that tip, but i do not know if anything like that. It may make sense since i got to turn on one heater after rebooting HA. Strange.

**Comment by solve-salvesen** [comment]
Not to be nagging, but documentation can be good for the future also :-) .

Maybe something doing with ESPHome version also. I have 10.2 for now. But the HA installasjon at home is the same at in the cabin, also ESP versions, the mill.h as well. And the D1 Mini. Very strange. I have experienced this before as well, but it started working again.

I notice the 
  **current_temperature: nan
  target_temperature: nan**

and not 
  **current_temperature: 19
  target_temperature: 18**
  
This is logged when not doing anything (the one not working on the left, and one at home to the right):
![2024-11-08 13_06_27-WinMerge -  Venstre uten tittel - Høyre uten tittel](https://github.com/user-attachments/assets/8ab8592f-3b40-46b5-a6fa-b069eaeff4ce)

This is loggend when turning to heat (the one not working on the left, and one at home to the right):
![2024-11-08 13_06_15-WinMerge -  Venstre uten tittel - Høyre uten tittel](https://github.com/user-attachments/assets/002aa867-bca5-44fc-930c-4f2f072ae802)

**Comment by JDolven** [comment]
You can remove comments in mill.h to receive responses from the oven. Decoding requires a bit of work, but the read temperature should be element 7, and the target temperature should be element 6. It might be worth checking if they come as NaN or another value from the ovens.
`          //for (int element : receivedChars) { // for each element in the array
          //ESP_LOGI("Recivedbytes", "%x", receivedChars[element ]);
          //}`

**Comment by solve-salvesen** [comment]
I have not come to a conclusion, but the heaters seems to be working again. I will restart the heaters manually tonight and will monitor them.

**Comment by solve-salvesen** [comment]
Not getting closer a solution. Seems unstable, the good thing is that heater turns on (read that from AMS Reader). It is strange that this happens on 3 heaters at my cabin, but 4 heaters at home with the same setup of wifi and everything works good. Very strange. I have checked HA and nothing there should do this. 

The behavior is also when i change directly in the web gui of the heater, but I will try to disable device in HA, and then change directly in the web gui on the heater.

**Comment by solve-salvesen** [comment]
Seems to be something with HA, but don't know what. Will investigate further :-).

HA turns on, but off immediately, but Web GUI is on heat. When combining change in termperatur and HEAT it seams to work, but HA in no neccesarily following.

**Comment by solve-salvesen** [comment]
I think I have found a solution to my problems in my cabin. Mushroom Climate card seems to be the issue. After removing this from my dashboards everything seems to be working perfectly again. A bit strange, but maybe some Web GUI updates or something going on, I don't know for sure. So far, so good!
