### ISSUE TITLE
Esp32-s3-zero

### ISSUE THREAD

**Issue by solve-salvesen** [JDolven/Replacing-HF_LPT120A-in-a-millheat-heater#7]
Have anyone tried to get this working with an ESP32? In my case I have several ESP32-S3-Zero (https://www.waveshare.com/wiki/ESP32-S3-Zero) and trying to replace Wemos D1 Mini with those, but I am having issues getting data from the heater.

I have tried several things, but has ended up with this UART config:
uart:
  id: uart_bus
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 9600

This is not working so my hope is that someone has tried this befor me :-)

**Comment by JDolven** [comment]
![image](https://github.com/user-attachments/assets/c2334b2b-9367-43f4-9657-f88bb2cdb3e9)
Is it correct that 3V3 on the S3 Zero is output only? It seems like it requires 5V to operate
